DefaultContentLanguage = "de"
baseURL = "https://fte-13.netlify.app"
languageCode = "de"
removePathAccents = true
theme = "infinity-hugo"
title = "FTE"
[copyright]
0 = "C"
1 = "o"
10 = "©"
11 = " "
12 = "F"
13 = "T"
14 = "E"
15 = " "
16 = "2"
17 = "0"
18 = "2"
19 = "0"
2 = "p"
3 = "y"
4 = "r"
5 = "i"
6 = "g"
7 = "h"
8 = "t"
9 = " "
other = "Copyright © FTE"
[languages.de]
contentDir = "content"
title = "FTE"
weight = 1
[params]
customHead = ""
[params.about]
description = "Ich bin in meiner Freizeit als Entwickler und Designer unterwegs. Ich bin Mitgründer des [LXDB](https://web.lxdb.de)-Teams und bin dort hauptsächlich für die Uploads im Bereich [Arduino](https://www.arduino.cc) zuständig. "
enable = true
heading = "Über mich"
sliderItem = []
[params.contact]
enable = true
subtitle = "kontaktieren Sie mich hier:"
title = "Kontakt"
[params.cta]
bg = "/images/lapis.jpg"
enable = false
subtitle = ""
title = ""
[params.hero]
bg = "/images/img_0065.JPG"
btnText = "Services"
countdownDay = "31"
countdownMonth = "12"
countdownYear = "2020"
disableCountdown = true
enable = true
subtitle = "Entwickler & Designer"
title = "Fabian Ecke"
[params.navigation]
about = "Über"
contact = "Kontakt"
home = "Startseite"
logo = "/images/logo-transparent.png"
service = "Service"
[params.service]
enable = true
subtitle = ""
title = "Services"
[[params.service.serviceItem]]
delay = "0s"
description = "Auf den Youtube-Kanälen f_t_e und LXDB stelle ich Videos und Tutorials rund um das Thema Arduino & selbstgebaute Alltags-Gegenstände online."
icon = "tf-genius"
title = "Alltags-Projekte"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Ich bin auf das Feedback von Zuschauern angewiesen. Ich gehe gerne auf Projektwünsche und Anfragen für bestimmte Programme/Sketche ein und werde sie auch im Rahmen meiner Möglichkeiten bearbeiten."
icon = "tf-ion-android-people"
title = "Feedback"
